name: vehicle3.7
channels:
  - pdrops
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - asn1crypto=0.24.0=py37_0
  - astor=0.8.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37h1ba5d50_0
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py37_0
  - glib=2.56.2=hd408876_0
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - influxdb=5.2.2=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.7.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.3=py37_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.0=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_1
  - pandas=0.25.0=py37he6710b0_0
  - parso=0.5.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.1.1=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - scipy=1.3.0=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - atari-py==0.2.6
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - click==7.0
    - cloudpickle==1.2.2
    - colorama==0.4.1
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.17.1
    - gym==0.14.0
    - importlib-metadata==0.22
    - jsonschema==3.0.2
    - kdtree==0.16
    - lz4==2.1.10
    - more-itertools==7.2.0
    - opencv-python==4.1.1.26
    - opencv-python-headless==4.1.1.26
    - packaging==19.1
    - pillow==6.1.0
    - pluggy==0.13.0
    - prettytable==0.7.2
    - protobuf==3.9.1
    - psutil==5.6.3
    - py==1.8.0
    - py-spy==0.1.11
    - pyglet==1.3.2
    - pyrsistent==0.15.4
    - pytest==5.1.2
    - pyyaml==5.1.2
    - ray==0.7.4
    - redis==3.3.8
    - setproctitle==1.1.10
    - utm==0.5.0
    - zipp==0.6.0
prefix: /home/user/.conda/envs/vehicle3.7

